name: Proposals
description: Proposal sumbission for new TODO initiatives
title: "[Proposal]: "
labels: "Proposal"
body:
- type: markdown
  attributes:
    value: |
      This is a proposal sumbission for new TODO initiatives that are not already implemented in any existing TODO Resourcces. if you'd like to add resources for an existing TODO initative (e.g New TODO Guides, new OSPO Case Study, OSPOlogy session, etc) please check TODO [contribution guidelines](https://github.com/todogroup/todogroup.org#-adding-resources). If that's not the case, please file the new initiative using this issue form. Once the issue is submitted, someone from the SC or the TODO PM will review the proposal ASAP.        
- type: textarea
  id: proposal-title
  attributes:
    label: Proposal Title
    description: Please provide the desired title for your proposal
    value: "For instance, create an awesome open source management working group"
  validations:
    required: true
- type: textarea
  id: proposal-goal
  attributes:
    label: Proposal Goal
    description: Please assign a goal for your proposal
    value: "For instance, improve community engagement between open source leaders and help create quality resources"
  validations:
    required: true
- type: textarea
  id: proposal-description
  attributes:
    label: Proposal Description
    description: Please provide a description for your proposal
    value: "For instance, I'd like to create the awesome working group to sync with other interested communitiy members on how to do awesome open source management"
  validations:
    required: true
- type: textarea
  id: proposal-action-items
  attributes:
    label: Proposal Action Items
    description: What set of action items should be accomplished in this proposal in order to succeed?
    value: "For instance, organize bi-weekly sync calls, build a todo guide that shows the work done in this working group"
  validations:
    required: true
- type: checkboxes
  id: check
  attributes:
    label: conditions
    description: By submitting this issue, you have checked the [current TODO initiatives](https://github.com/todogroup) and confirm that your proposal is not already implemented in any existing TODO initiative.
    options:
    - label: I have checked the existing TODO initiatives and confirm that my proposal is not implemented in any existing TODO initiative.
      required: true
